### ISSUE TITLE
How to do inference with the model ?

### ISSUE THREAD

**Issue by dtsonov** [shulmaneyal/metatrees#1]
Hi, i did see the code, and my question is how I can do example inference with it.
For exmaple the current implementaion of 'forward' method requires **users**, **items** and **x** feture vector.
In case of inference what values needed for **users** and **items** ? They have the batch size.
According to the paper, I guess that the input will be 1 usre's, item's data and some feature data. Correct ?

**Comment by shulmaneyal** [comment]
Hi, you'll need to provide the whole training set of the user (x and y) and the example you wish to run inference for as a set. The signature is model(x_train, y_train, x_test). See here https://github.com/shulmaneyal/metatrees/blob/004c166785ae3a86ea054600fa29fc0aa0e9daaf/batch/evaluation.py#L56
